apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-application-db
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/joaquin-solari/infra-repo.git
    path: database
    helm:
      valueFiles:
         - environments/values-dev.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: db-dev
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      # prune hace que Argo borre los componentes borrados del repo. Si esto estuviese en false y borramos un deployment.yaml del repo, el deployment seguiria existiendo en el cluster
      prune: true
        # selfHeal hace que cada vez que haya un cambio manual en el cluster, por ejemplo borrar un pod con kubectl, Argo anule y restaure el cluster a lo que dice el repo
      selfHeal: true

